version: "3"

services:
  mysql:
    build: ./mysql
    container_name: mysql_crm
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql/
    env_file:
      - ./mysql.env
    restart: always

  django:
    build: ./src
    container_name: crm_django
    command: uwsgi --ini /code/crm/django.ini
    volumes:
      - ./src:/code
    expose:
      - 8001
    env_file:
      - ./django.env
    restart: always

  nginx:
    image: nginx:1.19.5-alpine
    container_name: crm_nginx
    volumes:
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
      - ./src/static:/static
    depends_on:
      - django
    restart: always

volumes:
  mysql_data:

networks:
  default:
    external:
      name: shared
